spring.application.name=jobqueue

spring.datasource.url=jdbc:postgresql://localhost:5433/jobs
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.flyway.enabled=true
spring.flyway.schemas=jobs
spring.flyway.default-schema=jobs
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.default_schema=jobs

spring.jackson.property-naming-strategy=SNAKE_CASE
server.port=3000


logging.level.org.springframework.web=DEBUG
logging.level.web=DEBUG

logging.level.org.flywaydb=DEBUG

logging.level.org.springframework.boot.context.config=TRACE